### ISSUE TITLE
Switch to production DB failing

### ISSUE THREAD

**Issue by andyelsen** [LINCnil/pia-back#107]
Hi, i am not able to switch to production DB. The test and Development DB's are ok and working.

When using this command: RAILS_ENV=production bin/rake db:create

i get this error:

ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `rails credentials:edit`
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-6.0.3.4/lib/rails/application.rb:588:in `validate_secret_key_base'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-6.0.3.4/lib/rails/application.rb:423:in `secret_key_base'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-6.0.3.4/lib/rails/application.rb:177:in `key_generator'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-6.0.3.4/lib/rails/application.rb:201:in `message_verifier'
/usr/local/rvm/gems/ruby-2.6.6/gems/activestorage-6.0.3.4/lib/active_storage/engine.rb:97:in `block (2 levels) in <class:Engine>'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-6.0.3.4/lib/active_support/lazy_load_hooks.rb:68:in `block in execute_hook'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-6.0.3.4/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-6.0.3.4/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-6.0.3.4/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-6.0.3.4/lib/active_support/lazy_load_hooks.rb:51:in `each'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-6.0.3.4/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-6.0.3.4/lib/rails/application/finisher.rb:129:in `block in <module:Finisher>'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `run'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-6.0.3.4/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-6.0.3.4/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-6.0.3.4/lib/rails/application.rb:363:in `initialize!'
/opt/pia-back/config/environment.rb:5:in `<main>'
/usr/local/rvm/gems/ruby-2.6.6/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/local/rvm/gems/ruby-2.6.6/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/local/rvm/gems/ruby-2.6.6/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/rvm/gems/ruby-2.6.6/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/usr/local/rvm/gems/ruby-2.6.6/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
/usr/local/rvm/gems/ruby-2.6.6/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-6.0.3.4/lib/rails/application.rb:339:in `require_environment!'
/usr/local/rvm/gems/ruby-2.6.6/gems/railties-6.0.3.4/lib/rails/application.rb:523:in `block in run_tasks_blocks'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)

Please proovide me some help.

Best regards.

**Comment by andyelsen** [comment]
I found it now. thx for closing
