### ISSUE TITLE
Erreur d'installation PIA-BACK

### ISSUE THREAD

**Issue by dbenoiton** [LINCnil/pia-back#13]
Bonjour,

J'ai une erreur lorsque je lance la commande bin/rake db:create

```
DEPRECATION WARNING: The factory_girl gem is deprecated. Please upgrade to factory_bot. See https://github.com/thoughtbot/factory_bot/blob/v4.9.0/UPGRADE_FROM_FACTORY_GIRL.md for further instructions. (called from <top (required)> at /var/lib/gems/2.3.0/gems/factory_girl-4.9.0/lib/factory_girl.rb:158)
root@SRVPIA:~/pia-back# /root/pia-back/config/environments/development.rb:46:in `block in <top (required)>': uninitialized constant ActiveSupport::EventedFileUpdateChecker (NameError)
        from /usr/lib/ruby/vendor_ruby/rails/railtie.rb:210:in `instance_eval'
        from /usr/lib/ruby/vendor_ruby/rails/railtie.rb:210:in `configure'
        from /root/pia-back/config/environments/development.rb:1:in `<top (required)>'
        from /usr/lib/ruby/vendor_ruby/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
        from /usr/lib/ruby/vendor_ruby/rails/engine.rb:597:in `each'
        from /usr/lib/ruby/vendor_ruby/rails/engine.rb:597:in `block in <class:Engine>'
        from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `instance_exec'
        from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `run'
        from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:55:in `block in run_initializers'
        from /usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
        from /usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
        from /usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
        from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:44:in `each'
        from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:44:in `tsort_each_child'
        from /usr/lib/ruby/2.3.0/tsort.rb:415:in `call'
        from /usr/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
        from /usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
        from /usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
        from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
        from /usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
        from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:54:in `run_initializers'
        from /usr/lib/ruby/vendor_ruby/rails/application.rb:352:in `initialize!'
        from /root/pia-back/config/environment.rb:5:in `<top (required)>'
        from /usr/lib/ruby/vendor_ruby/spring/application.rb:92:in `require'
        from /usr/lib/ruby/vendor_ruby/spring/application.rb:92:in `preload'
        from /usr/lib/ruby/vendor_ruby/spring/application.rb:143:in `serve'
        from /usr/lib/ruby/vendor_ruby/spring/application.rb:131:in `block in run'
        from /usr/lib/ruby/vendor_ruby/spring/application.rb:125:in `loop'
        from /usr/lib/ruby/vendor_ruby/spring/application.rb:125:in `run'
        from /usr/lib/ruby/vendor_ruby/spring/application/boot.rb:18:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'
```
Pouvez-vous m'aider svp.
Cordialement,

**Comment by ylachgar** [comment]
Bonjour @dbenoiton 

Lorsque tu lances la commande : apt-cache policy ruby quel est le resultat ?

**Comment by dbenoiton** [comment]
Bonjour,
voici le résultat : 
ruby:
 Installé : 1:2.3.3
 Candidat : 1:2.3.3
Table de version : 
*** 1:2.3.3 500
500 http://ftp.fr.debian.org/debian stretch/main amd64 Packages
100 /var/lib/dpkg/status

**Comment by ylachgar** [comment]
Hi All,

Please find in below attachment the full runbook for PIA Back and Front with ubuntu 17.10
[PIA Technical Runbook.docx](https://github.com/LINCnil/pia-back/files/1723454/PIA.Technical.Runbook.docx)

**Comment by Spartacus2018** [comment]
Bonjour, 

merci pour ce guide, 
est il possible d'utiliser une version d'ubuntu LTS et non une version qui à un support qui termine dans 9 mois ?

**Comment by ylachgar** [comment]
Bonjour @Spartacus2018 ,

Il me semble que cela devrais fonctionner sur la version LTS sans problème , je vais essayer de mon coté :) et update la doc, je vais également checker pour CentOS

**Comment by brunto** [comment]
Bonjour,
Cela se produit quand la version de rails n'est pas similaire à celle utilisée pour le projet.
En étant dans le répertoire du projet `pia-back` que vous donne le résultat de la commande `bin/rails -v` et `rails -v` ?
La première devrait vous retourner un numéro de version commençant par 5.0.X

**Comment by dbenoiton** [comment]
BOnjour,

Désolé pour le retard.
Un grand merci pour le book.
Je rencontre encore un problème, le front ne se lance qu'en mode développement (ng serve -host XXX.XXX.XXX.XXX -port 8083)
Quand j'essai ```
ng serve -e prod -host XXX.XXX.XXX.XXX -port 8083
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (/home/dbenoiton/pia/node_modules/typescript/lib/typescr                                                                                                                                                                                        ipt.js:16640:109)
    at parseSourceFileWorker (/home/dbenoiton/pia/node_modules/typescript/lib/ty                                                                                                                                                                                        pescript.js:16572:26)
    at Object.parseSourceFile (/home/dbenoiton/pia/node_modules/typescript/lib/t                                                                                                                                                                                        ypescript.js:16521:26)
    at Object.createSourceFile (/home/dbenoiton/pia/node_modules/typescript/lib/                                                                                                                                                                                        typescript.js:16371:29)
    at VirtualFileStats.getSourceFile (/home/dbenoiton/pia/node_modules/@ngtools                                                                                                                                                                                        /webpack/src/compiler_host.js:67:35)
    at WebpackCompilerHost.getSourceFile (/home/dbenoiton/pia/node_modules/@ngto                                                                                                                                                                                        ols/webpack/src/compiler_host.js:206:38)
    at findSourceFile (/home/dbenoiton/pia/node_modules/typescript/lib/typescrip                                                                                                                                                                                        t.js:70246:29)
    at processImportedModules (/home/dbenoiton/pia/node_modules/typescript/lib/t                                                                                                                                                                                        ypescript.js:70393:25)
    at findSourceFile (/home/dbenoiton/pia/node_modules/typescript/lib/typescrip                                                                                                                                                                                        t.js:70274:17)
    at processImportedModules (/home/dbenoiton/pia/node_modules/typescript/lib/t                                                                                                                                                                                        ypescript.js:70393:25)
    at findSourceFile (/home/dbenoiton/pia/node_modules/typescript/lib/typescrip                                                                                                                                                                                        t.js:70274:17)
    at processImportedModules (/home/dbenoiton/pia/node_modules/typescript/lib/t                                                                                                                                                                                        ypescript.js:70393:25)
    at findSourceFile (/home/dbenoiton/pia/node_modules/typescript/lib/typescrip                                                                                                                                                                                        t.js:70274:17)
    at args (/home/dbenoiton/pia/node_modules/typescript/lib/typescript.js:70200                                                                                                                                                                                        :85)
    at getSourceFileFromReferenceWorker (/home/dbenoiton/pia/node_modules/typesc                                                                                                                                                                                        ript/lib/typescript.js:70173:34)
    at processSourceFile (/home/dbenoiton/pia/node_modules/typescript/lib/typesc                                                                                                                                                                                        ript.js:70200:13)


```

**Comment by brunto** [comment]
Bonjour,
Je viens de mettre à jour le fichier README via une Pull Request afin de préciser la procédure : https://github.com/LINCnil/pia/pull/137/files
