### ISSUE TITLE
Error 404 : env_production

### ISSUE THREAD

**Issue by jgrossemy** [LINCnil/pia-back#2]
En environnement de production (en developpement cela fonctionne bien), l'appel GET à l'index du serveur renvoit une erreur 404 avec le log suivant côté serveur :
>I, [2017-12-01T15:38:24.180155 #29]  INFO -- : [2d77470e-4d26-44e9-9224-5583dc021282] Started GET "/" for 10.XX.XX.XX at 2017-12-01 15:38:24 +0000
F, [2017-12-01T15:38:24.180624 #29] FATAL -- : [2d77470e-4d26-44e9-9224-5583dc021282]
F, [2017-12-01T15:38:24.180664 #29] FATAL -- : [2d77470e-4d26-44e9-9224-5583dc021282] ActionController::RoutingError (No route matches [GET] "/"):
F, [2017-12-01T15:38:24.180685 #29] FATAL -- : [2d77470e-4d26-44e9-9224-5583dc021282]
F, [2017-12-01T15:38:24.180709 #29] FATAL -- : [2d77470e-4d26-44e9-9224-5583dc021282] actionpack (5.0.6) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
[2d77470e-4d26-44e9-9224-5583dc021282] actionpack (5.0.6) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
[2d77470e-4d26-44e9-9224-5583dc021282] railties (5.0.6) lib/rails/rack/logger.rb:36:in `call_app'
[2d77470e-4d26-44e9-9224-5583dc021282] railties (5.0.6) lib/rails/rack/logger.rb:24:in `block in call'
[2d77470e-4d26-44e9-9224-5583dc021282] activesupport (5.0.6) lib/active_support/tagged_logging.rb:69:in `block in tagged'
[2d77470e-4d26-44e9-9224-5583dc021282] activesupport (5.0.6) lib/active_support/tagged_logging.rb:26:in `tagged'
[2d77470e-4d26-44e9-9224-5583dc021282] activesupport (5.0.6) lib/active_support/tagged_logging.rb:69:in `tagged'
[2d77470e-4d26-44e9-9224-5583dc021282] railties (5.0.6) lib/rails/rack/logger.rb:24:in `call'
[2d77470e-4d26-44e9-9224-5583dc021282] actionpack (5.0.6) lib/action_dispatch/middleware/request_id.rb:24:in `call'
[2d77470e-4d26-44e9-9224-5583dc021282] rack (2.0.3) lib/rack/runtime.rb:22:in `call'
[2d77470e-4d26-44e9-9224-5583dc021282] activesupport (5.0.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
[2d77470e-4d26-44e9-9224-5583dc021282] actionpack (5.0.6) lib/action_dispatch/middleware/executor.rb:12:in `call'
[2d77470e-4d26-44e9-9224-5583dc021282] rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
[2d77470e-4d26-44e9-9224-5583dc021282] rack-cors (1.0.1) lib/rack/cors.rb:93:in `call'
[2d77470e-4d26-44e9-9224-5583dc021282] railties (5.0.6) lib/rails/engine.rb:522:in `call'
[2d77470e-4d26-44e9-9224-5583dc021282] puma (3.10.0) lib/puma/configuration.rb:225:in `call'
[2d77470e-4d26-44e9-9224-5583dc021282] puma (3.10.0) lib/puma/server.rb:605:in `handle_request'
[2d77470e-4d26-44e9-9224-5583dc021282] puma (3.10.0) lib/puma/server.rb:437:in `process_client'
[2d77470e-4d26-44e9-9224-5583dc021282] puma (3.10.0) lib/puma/server.rb:301:in `block in run'
[2d77470e-4d26-44e9-9224-5583dc021282] puma (3.10.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
>

**Comment by brunto** [comment]
Bonjour,
La mise en production d'une application Rails doit suivre la procédure suivante : 
1. Mise à jour de la section "production" dans le fichier `database.yml`
2. La création de la base de données : `RAILS_ENV=production rake db:create`
3. La création des tables : `RAILS_ENV=production rake db:migrate`
4. La compilation des assets : `RAILS_ENV=production rake assets:precompile`
5. Le lancement du serveur : `RAILS_ENV=production bin/rails s`

**Comment by jgrossemy** [comment]
Merci,

Je vais redéployer avec les étapes qu'il me manquait.
