### ISSUE TITLE
Problème lors de l'installation de PIA Front

### ISSUE THREAD

**Issue by bgu19** [LINCnil/pia-back#204]
Bonjour, 

j'essaye d'installer l'application Pia en suivant la doc dans le wiki https://github.com/LINCnil/pia-back/wiki

tout fonctionne bien sauf l'installation du front ou j'ai une erreur lors de l'install (yarn install)

error /var/www/pia/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /var/www/pia/node_modules/electron
Output:
RequestError: connect ETIMEDOUT 140.82.121.3:443
    at ClientRequest.<anonymous> (/var/www/pia/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:412:35)
    at ClientRequest.origin.emit (/var/www/pia/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)

![image](https://user-images.githubusercontent.com/126561332/221810407-c6371f39-d287-44fd-885b-de8816dcab50.png)

j'ai tout essayé sans succès.
quelqu'un pourrait m'aider pour résoudre ce problème svp ? 

Je vous remercie.

Cordialement,

**Comment by syl-p** [comment]
Bien sur ! Quel est votre version de Nodejs ?

**Comment by bgu19** [comment]
Bonjour, 
j'ai pu résoudre le souci en ouvrant (temporairement) directement les flux vers les répo nodejs et pas en passant par le proxy, (ça ne fonctionne pas à travers le proxy même en exportant la variable d'env)
