### ISSUE TITLE
JSON::ParserError (784: unexpected token at '""') after update to version 2.0.0

### ISSUE THREAD

**Issue by gnieser** [LINCnil/pia-back#46]
Hello,

After updating front and back applications from version 1.6.4 to 2.0.0, the creation of a new entry fails.
The POST request to /pias results in a 500 Internal Server Error.

```
I, [2018-12-13T09:55:59.367832 #24252]  INFO -- : [9c27197b-0a35-4471-a696-972937dd5f66] Started POST "/pias" for 127.0.0.1 at 2018-12-13 09:55:59 +0100
I, [2018-12-13T09:55:59.370565 #24252]  INFO -- : [9c27197b-0a35-4471-a696-972937dd5f66] Processing by PiasController#create as */*
I, [2018-12-13T09:55:59.370671 #24252]  INFO -- : [9c27197b-0a35-4471-a696-972937dd5f66]   Parameters: {"pia"=>{"name"=>"test", "author_name"=>"test", "evaluator_name"=>"test", "validator_name"=>"test", "dpo_status"=>"undefined", "dpo_opinion"=>"undefined", "concerned_people_opinion"=>"undefined", "concerned_people_status"=>"undefined", "rejected_reason"=>"undefined", "applied_adjustements"=>"undefined", "created_at"=>"Thu Dec 13 2018 09:56:00 GMT+0100 (Central European Standard Time)", "updated_at"=>"undefined", "status"=>"0", "is_example"=>"0", "dpos_names"=>"undefined", "people_names"=>"undefined", "concerned_people_searched_opinion"=>"undefined", "concerned_people_searched_content"=>"undefined", "structure_id"=>"", "structure_name"=>"undefined", "structure_sector_name"=>"undefined", "structure_data"=>"\"\""}}
I, [2018-12-13T09:55:59.372085 #24252]  INFO -- : [9c27197b-0a35-4471-a696-972937dd5f66] Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms)
F, [2018-12-13T09:55:59.372774 #24252] FATAL -- : [9c27197b-0a35-4471-a696-972937dd5f66]
F, [2018-12-13T09:55:59.372833 #24252] FATAL -- : [9c27197b-0a35-4471-a696-972937dd5f66] JSON::ParserError (784: unexpected token at '""'):
F, [2018-12-13T09:55:59.372869 #24252] FATAL -- : [9c27197b-0a35-4471-a696-972937dd5f66]
F, [2018-12-13T09:55:59.372905 #24252] FATAL -- : [9c27197b-0a35-4471-a696-972937dd5f66] app/controllers/pias_controller.rb:30:in `create'
```

Chrome shows the folloying request content being sent :
```
-----WebKitFormBoundaryF35LfFh31pBo4d0J
Content-Disposition: form-data; name="pia[name]"
 
test
------WebKitFormBoundaryF35LfFh31pBo4d0J
Content-Disposition: form-data; name="pia[author_name]"
 
test
------WebKitFormBoundaryF35LfFh31pBo4d0J
Content-Disposition: form-data; name="pia[evaluator_name]"
 
test
------WebKitFormBoundaryF35LfFh31pBo4d0J
Content-Disposition: form-data; name="pia[validator_name]"
 
test
------WebKitFormBoundaryF35LfFh31pBo4d0J
Content-Disposition: form-data; name="pia[dpo_status]"
 
undefined
------WebKitFormBoundaryF35LfFh31pBo4d0J
Content-Disposition: form-data; name="pia[dpo_opinion]"
 
undefined
------WebKitFormBoundaryF35LfFh31pBo4d0J
Content-Disposition: form-data; name="pia[concerned_people_opinion]"
 
undefined
------WebKitFormBoundaryF35LfFh31pBo4d0J
Content-Disposition: form-data; name="pia[concerned_people_status]"
 
undefined
------WebKitFormBoundaryF35LfFh31pBo4d0J
Content-Disposition: form-data; name="pia[rejected_reason]"
 
undefined
------WebKitFormBoundaryF35LfFh31pBo4d0J
Content-Disposition: form-data; name="pia[applied_adjustements]"
 
undefined
------WebKitFormBoundaryF35LfFh31pBo4d0J
Content-Disposition: form-data; name="pia[created_at]"
 
Thu Dec 13 2018 09:56:00 GMT+0100 (Central European Standard Time)
------WebKitFormBoundaryF35LfFh31pBo4d0J
Content-Disposition: form-data; name="pia[updated_at]"
 
undefined
------WebKitFormBoundaryF35LfFh31pBo4d0J
Content-Disposition: form-data; name="pia[status]"
 
0
------WebKitFormBoundaryF35LfFh31pBo4d0J
Content-Disposition: form-data; name="pia[is_example]"
 
0
------WebKitFormBoundaryF35LfFh31pBo4d0J
Content-Disposition: form-data; name="pia[dpos_names]"
 
undefined
------WebKitFormBoundaryF35LfFh31pBo4d0J
Content-Disposition: form-data; name="pia[people_names]"
 
undefined
------WebKitFormBoundaryF35LfFh31pBo4d0J
Content-Disposition: form-data; name="pia[concerned_people_searched_opinion]"
 
undefined
------WebKitFormBoundaryF35LfFh31pBo4d0J
Content-Disposition: form-data; name="pia[concerned_people_searched_content]"
 
undefined
------WebKitFormBoundaryF35LfFh31pBo4d0J
Content-Disposition: form-data; name="pia[structure_id]"
 
 
------WebKitFormBoundaryF35LfFh31pBo4d0J
Content-Disposition: form-data; name="pia[structure_name]"
 
undefined
------WebKitFormBoundaryF35LfFh31pBo4d0J
Content-Disposition: form-data; name="pia[structure_sector_name]"
 
undefined
------WebKitFormBoundaryF35LfFh31pBo4d0J
Content-Disposition: form-data; name="pia[structure_data]"
 
""
------WebKitFormBoundaryF35LfFh31pBo4d0J--
```

I suspect the "" value of pia[structure_data] is not being parsed correctly.
Could you please provide some help in investigating this issue?

Thanks and best regards !

**Comment by brunto** [comment]
Hello, I tried the same as yours without error. I think you're right, the error come from the "" inside structure_data but I can't reproduce. Could you comment the line 30 of the file `app/controllers/pias_controller.rb`, restart the rails server and then recreate a new PIA?

**Comment by gnieser** [comment]
Thanks for jumping in to help ! Much appreciated.

After commented the line 30 of app/controllers/pias_controller.rb
```
  # pia_parameters[:structure_data] = JSON.parse(pia_parameters[:structure_data]) if pia_parameters[:structure_data]
```

The creation succeeds:
```
I, [2018-12-13T11:12:54.518460 #24899]  INFO -- : [6f236644-ffc4-42d4-8fb6-73294caa50fa] Started POST "/pias" for 127.0.0.1 at 2018-12-13 11:12:54 +0100
I, [2018-12-13T11:12:54.519858 #24899]  INFO -- : [6f236644-ffc4-42d4-8fb6-73294caa50fa] Processing by PiasController#create as */*
I, [2018-12-13T11:12:54.519935 #24899]  INFO -- : [6f236644-ffc4-42d4-8fb6-73294caa50fa]   Parameters: {"pia"=>{"name"=>"test", "author_name"=>"test", "evaluator_name"=>"test", "validator_name"=>"test", "dpo_status"=>"undefined", "dpo_op
inion"=>"undefined", "concerned_people_opinion"=>"undefined", "concerned_people_status"=>"undefined", "rejected_reason"=>"undefined", "applied_adjustements"=>"undefined", "created_at"=>"Thu Dec 13 2018 11:12:55 GMT+0100 (Central European
 Standard Time)", "updated_at"=>"undefined", "status"=>"0", "is_example"=>"0", "dpos_names"=>"undefined", "people_names"=>"undefined", "concerned_people_searched_opinion"=>"undefined", "concerned_people_searched_content"=>"undefined", "s
tructure_id"=>"", "structure_name"=>"undefined", "structure_sector_name"=>"undefined", "structure_data"=>"\"\""}}
D, [2018-12-13T11:12:54.521495 #24899] DEBUG -- : [6f236644-ffc4-42d4-8fb6-73294caa50fa]    (0.1ms)  BEGIN
D, [2018-12-13T11:12:54.523416 #24899] DEBUG -- : [6f236644-ffc4-42d4-8fb6-73294caa50fa]   SQL (0.7ms)  INSERT INTO "pias" ("name", "author_name", "evaluator_name", "validator_name", "dpo_status", "dpo_opinion", "concern
ed_people_opinion", "concerned_people_status", "created_at", "updated_at", "dpos_names", "people_names", "concerned_people_searched_opinion", "concerned_people_searched_content", "structure_name", "structure_sector_name", "structure_data
") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17) RETURNING "id"  [["name", "test"], ["author_name", "test"], ["evaluator_name", "test"], ["validator_name", "test"], ["dpo_status", 0], ["dpo_opinio
n", "undefined"], ["concerned_people_opinion", "undefined"], ["concerned_people_status", 0], ["created_at", "2018-12-13 10:12:54.521715"], ["updated_at", "2018-12-13 10:12:54.521715"], ["dpos_names", "undefined"], ["people_names", "undef
ined"], ["concerned_people_searched_opinion", "t"], ["concerned_people_searched_content", "undefined"], ["structure_name", "undefined"], ["structure_sector_name", "undefined"], ["structure_data", "\"\\\"\\\"\""]]
D, [2018-12-13T11:12:54.524705 #24899] DEBUG -- : [6f236644-ffc4-42d4-8fb6-73294caa50fa]    (1.1ms)  COMMIT
I, [2018-12-13T11:12:54.525461 #24899]  INFO -- : [6f236644-ffc4-42d4-8fb6-73294caa50fa] [active_model_serializers] Rendered PiaSerializer with ActiveModelSerializers::Adapter::Attributes (0.4ms)
I, [2018-12-13T11:12:54.525610 #24899]  INFO -- : [6f236644-ffc4-42d4-8fb6-73294caa50fa] Completed 201 Created in 6ms (Views: 0.7ms | ActiveRecord: 1.9ms)
```

A subsequent error (silent from the browser perspective) can be seen in the log though for a PATCH request:
```
I, [2018-12-13T11:12:54.769722 #24899]  INFO -- : [beff6f18-1e5f-48f2-b808-6859083060ad] Started PATCH "/pias/6" for 127.0.0.1 at 2018-12-13 11:12:54 +0100
I, [2018-12-13T11:12:54.771005 #24899]  INFO -- : [beff6f18-1e5f-48f2-b808-6859083060ad] Processing by PiasController#update as */*
I, [2018-12-13T11:12:54.771098 #24899]  INFO -- : [beff6f18-1e5f-48f2-b808-6859083060ad]   Parameters: {"pia"=>{"id"=>"6", "status"=>"0", "name"=>"test", "author_name"=>"test", "evaluator_name"=>"test", "validator_name"=>"test", "dpo_sta
tus"=>"0", "dpo_opinion"=>"undefined", "dpos_names"=>"undefined", "people_names"=>"undefined", "concerned_people_opinion"=>"undefined", "concerned_people_status"=>"0", "rejection_reason"=>"", "applied_adjustments"=>"", "is_example"=>"0",
 "created_at"=>"2018-12-13T10:12:54.521Z", "updated_at"=>"Thu Dec 13 2018 11:12:55 GMT+0100 (Central European Standard Time)", "concerned_people_searched_opinion"=>"true", "concerned_people_searched_content"=>"undefined", "structure_id"=
>"", "structure_name"=>"undefined", "structure_sector_name"=>"undefined", "structure_data"=>"\"\\\"\\\"\"", "rejected_reason"=>"undefined", "applied_adjustements"=>"undefined"}, "id"=>"6"}
D, [2018-12-13T11:12:54.772221 #24899] DEBUG -- : [beff6f18-1e5f-48f2-b808-6859083060ad]   Pia Load (0.4ms)  SELECT  "pias".* FROM "pias" WHERE "pias"."id" = $1 LIMIT $2  [["id", 6], ["LIMIT", 1]]
I, [2018-12-13T11:12:54.773438 #24899]  INFO -- : [beff6f18-1e5f-48f2-b808-6859083060ad] Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.4ms)
F, [2018-12-13T11:12:54.773833 #24899] FATAL -- : [beff6f18-1e5f-48f2-b808-6859083060ad]
F, [2018-12-13T11:12:54.773873 #24899] FATAL -- : [beff6f18-1e5f-48f2-b808-6859083060ad] JSON::ParserError (784: unexpected token at '"\"\""'):
F, [2018-12-13T11:12:54.773923 #24899] FATAL -- : [beff6f18-1e5f-48f2-b808-6859083060ad]
F, [2018-12-13T11:12:54.773950 #24899] FATAL -- : [beff6f18-1e5f-48f2-b808-6859083060ad] app/controllers/pias_controller.rb:43:in `update'
```


I also commented line 43:
```
  # pia_parameters[:structure_data] = JSON.parse(pia_parameters[:structure_data]) if pia_parameters[:structure_data]
```
which solves the PATCH request.

```
I, [2018-12-13T11:17:47.700240 #25171]  INFO -- : [8cbb5925-e300-4c70-860f-c4b81ae6aa60] Started PATCH "/pias/7" for 127.0.0.1 at 2018-12-13 11:17:47 +0100
I, [2018-12-13T11:17:47.703729 #25171]  INFO -- : [8cbb5925-e300-4c70-860f-c4b81ae6aa60] Processing by PiasController#update as */*
I, [2018-12-13T11:17:47.703839 #25171]  INFO -- : [8cbb5925-e300-4c70-860f-c4b81ae6aa60]   Parameters: {"pia"=>{"id"=>"7", "status"=>"0", "name"=>"test", "author_name"=>"test", "evaluator_name"=>"test", "validator_name"=>"test", "dpo_sta
tus"=>"0", "dpo_opinion"=>"undefined", "dpos_names"=>"undefined", "people_names"=>"undefined", "concerned_people_opinion"=>"undefined", "concerned_people_status"=>"0", "rejection_reason"=>"", "applied_adjustments"=>"", "is_example"=>"0",
 "created_at"=>"2018-12-13T10:17:47.358Z", "updated_at"=>"Thu Dec 13 2018 11:17:48 GMT+0100 (Central European Standard Time)", "concerned_people_searched_opinion"=>"true", "concerned_people_searched_content"=>"undefined", "structure_id"=
>"", "structure_name"=>"undefined", "structure_sector_name"=>"undefined", "structure_data"=>"\"\\\"\\\"\"", "rejected_reason"=>"undefined", "applied_adjustements"=>"undefined"}, "id"=>"7"}
D, [2018-12-13T11:17:47.704858 #25171] DEBUG -- : [8cbb5925-e300-4c70-860f-c4b81ae6aa60]   Pia Load (0.2ms)  SELECT  "pias".* FROM "pias" WHERE "pias"."id" = $1 LIMIT $2  [["id", 7], ["LIMIT", 1]]
D, [2018-12-13T11:17:47.706033 #25171] DEBUG -- : [8cbb5925-e300-4c70-860f-c4b81ae6aa60]    (0.1ms)  BEGIN
D, [2018-12-13T11:17:47.708815 #25171] DEBUG -- : [8cbb5925-e300-4c70-860f-c4b81ae6aa60]   SQL (0.5ms)  UPDATE "pias" SET "structure_data" = $1, "updated_at" = $2 WHERE "pias"."id" = $3  [["structure_data", "\"\\\"\\\
\\\\"\\\\\\\"\\\"\""], ["updated_at", "2018-12-13 10:17:47.706849"], ["id", 7]]
I, [2018-12-13T11:17:47.709743 #25171]  INFO -- : [2056a8ab-2a24-42e2-9306-8cac5ced569e] Started GET "/pias/7/answers?reference_to=111" for 127.0.0.1 at 2018-12-13 11:17:47 +0100
I, [2018-12-13T11:17:47.710293 #25171]  INFO -- : [2056a8ab-2a24-42e2-9306-8cac5ced569e] Processing by AnswersController#index as */*
I, [2018-12-13T11:17:47.711073 #25171]  INFO -- : [1d05070f-7f66-48f7-a9d6-8392a9568a3a] Started GET "/pias/7/measures" for 127.0.0.1 at 2018-12-13 11:17:47 +0100
I, [2018-12-13T11:17:47.711738 #25171]  INFO -- : [1d05070f-7f66-48f7-a9d6-8392a9568a3a] Processing by MeasuresController#index as */*
I, [2018-12-13T11:17:47.711334 #25171]  INFO -- : [2056a8ab-2a24-42e2-9306-8cac5ced569e]   Parameters: {"reference_to"=>"111", "pia_id"=>"7"}
D, [2018-12-13T11:17:47.711424 #25171] DEBUG -- : [8cbb5925-e300-4c70-860f-c4b81ae6aa60]    (2.3ms)  COMMIT
I, [2018-12-13T11:17:47.711795 #25171]  INFO -- : [1d05070f-7f66-48f7-a9d6-8392a9568a3a]   Parameters: {"pia_id"=>"7"}
```

Let me know whether further information is needed.

Thanks a lot !

**Comment by brunto** [comment]
Perfect, it's strange because I don't have the same behaviour!
Could you do a last test? Could you uncomment these lines, create a model and then create a PIA with this model to see if everything works fine.

**Comment by gnieser** [comment]
With the original app/controllers/pias_controller.rb non-commented, creating a model and then a PIA with this model works fine.  The issue with "" value of structure_data only appears when no model is selected.

**Comment by gnieser** [comment]
Users are reporting that they are facing the same issue when using the import pia feature. I can relate to error  JSON::ParserError (784: unexpected token at '""') in log in a previously commented line (app/controllers/pias_controller.rb:30:in `create'). It looks to me that it is the same error as a create pia without model.

**Comment by brunto** [comment]
After some investigation the problem come when you use the version 2.3.0 of ruby.
You must switch to a newest version (2.5.3). Do not use the 2.6.0 version for now.

**Comment by Nakilon** [comment]
Relevant link for those who are googling the exception: https://github.com/flori/json/issues/309
