### ISSUE TITLE
Problems when i rails server, and for db:create db:migrate

### ISSUE THREAD

**Issue by Mands59** [LINCnil/pia-back#63]
Hi, 

Please can you help me it's urgent, I have a problem, even after doing all the steps, when I run the command "RAILS_ENV=production bin/rake db:create" or migrate, i get this: 

```
/mnt/c/Users/administrateur/pia-back/config/initializers/cors.rb:10:in `block (2 levels) in <top (required)>': undefined method `split' for nil:NilClass (NoMethodError)
        from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/rack-cors-1.0.2/lib/rack/cors.rb:62:in `instance_eval'
        from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/rack-cors-1.0.2/lib/rack/cors.rb:62:in `allow'
        from /mnt/c/Users/administrateur/pia-back/config/initializers/cors.rb:9:in `block in <top (required)>'
/mnt/c/Users/administrateur/pia-back$      from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/rack-cors-1.0.2/lib/rack/cors.rb:47:in `instance_eval'
        from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/rack-cors-1.0.2/lib/rack/cors.rb:47:in `initialize'
     from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/stack.rb:35:in `new'
        from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/stack.rb:35:in `build'
        from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/stack.rb:100:in `block in build'
        from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/stack.rb:100:in `each'
        from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/stack.rb:100:in `inject'
        from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/stack.rb:100:in `build'
        from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/railties-5.0.7.2/lib/rails/engine.rb:508:in `block in app'
        from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/railties-5.0.7.2/lib/rails/engine.rb:504:in `synchronize'
        from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/railties-5.0.7.2/lib/rails/engine.rb:504:in `app'
        from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/railties-5.0.7.2/lib/rails/application/finisher.rb:37:in `block in <module:Finisher>'
        from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/railties-5.0.7.2/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/railties-5.0.7.2/lib/rails/initializable.rb:30:in `run'
        from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/railties-5.0.7.2/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /home/administrateur/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
        from /home/administrateur/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /home/administrateur/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /home/administrateur/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /home/administrateur/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:347:in `each'
        from /home/administrateur/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:347:in `call'
        from /home/administrateur/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
        from /home/administrateur/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
        from /home/administrateur/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
        from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/railties-5.0.7.2/lib/rails/initializable.rb:54:in `run_initializers'
        from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/railties-5.0.7.2/lib/rails/application.rb:352:in `initialize!'
        from /mnt/c/Users/administrateur/pia-back/config/environment.rb:5:in `<top (required)>'
        from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/spring-2.0.2/lib/spring/application.rb:102:in `require'
        from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/spring-2.0.2/lib/spring/application.rb:102:in `preload'
        from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
        from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
        from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
        from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
        from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /home/administrateur/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/administrateur/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from -e:1:in `<main>'

```

also, when i run the command "rails s", I get this:

```
DEPRECATION WARNING: The factory_girl gem is deprecated. Please upgrade to factory_bot. See https://github.com/thoughtbot/factory_bot/blob/v4.9.0/UPGRADE_FROM_FACTORY_GIRL.md for further instructions. (called from <top (required)> at /mnt/c/Users/administrateur/pia-back/config/application.rb:17)
=> Booting Puma
=> Rails 5.0.7.2 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Exiting
Traceback (most recent call last):
        63: from bin/rails:3:in `<main>'
        62: from bin/rails:3:in `load'
        61: from /mnt/c/Users/administrateur/pia-back/bin/spring:15:in `<top (required)>'
        60: from /mnt/c/Users/administrateur/pia-back/bin/spring:15:in `require'
        59: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
        58: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
        57: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
        56: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
        55: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
        54: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
        53: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
        52: from /mnt/c/Users/administrateur/pia-back/bin/rails:9:in `<top (required)>'
        51: from /mnt/c/Users/administrateur/pia-back/bin/rails:9:in `require'
        50: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/railties-5.0.7.2/lib/rails/commands.rb:18:in `<top (required)>'
        49: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        48: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:85:in `server'
        47: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:85:in `tap'
        46: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/railties-5.0.7.2/lib/rails/commands/commands_tasks.rb:90:in `block in server'
        45: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/railties-5.0.7.2/lib/rails/commands/server.rb:102:in `start'
        44: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/railties-5.0.7.2/lib/rails/commands/server.rb:148:in `log_to_stdout'
        43: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/rack-2.0.6/lib/rack/server.rb:354:in `wrapped_app'
        42: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/railties-5.0.7.2/lib/rails/commands/server.rb:84:in `app'
        41: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/rack-2.0.6/lib/rack/server.rb:219:in `app'
        40: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/rack-2.0.6/lib/rack/server.rb:319:in `build_app_and_options_from_config'
        39: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/rack-2.0.6/lib/rack/builder.rb:40:in `parse_file'
        38: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/rack-2.0.6/lib/rack/builder.rb:49:in `new_from_string'
        37: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/rack-2.0.6/lib/rack/builder.rb:49:in `eval'
        36: from /mnt/c/Users/administrateur/pia-back/config.ru:in `<main>'
        35: from /mnt/c/Users/administrateur/pia-back/config.ru:in `new'
        34: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
        33: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
        32: from /mnt/c/Users/administrateur/pia-back/config.ru:3:in `block in <main>'
        31: from /mnt/c/Users/administrateur/pia-back/config.ru:3:in `require_relative'
        30: from /mnt/c/Users/administrateur/pia-back/config/environment.rb:5:in `<top (required)>'
        29: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/railties-5.0.7.2/lib/rails/application.rb:352:in `initialize!'
        28: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/railties-5.0.7.2/lib/rails/initializable.rb:54:in `run_initializers'
        27: from /home/administrateur/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
        26: from /home/administrateur/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
        25: from /home/administrateur/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
        24: from /home/administrateur/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:347:in `call'
        23: from /home/administrateur/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:347:in `each'
        22: from /home/administrateur/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
        21: from /home/administrateur/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
        20: from /home/administrateur/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        19: from /home/administrateur/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
        18: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/railties-5.0.7.2/lib/rails/initializable.rb:55:in `block in run_initializers'
        17: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/railties-5.0.7.2/lib/rails/initializable.rb:30:in `run'
        16: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/railties-5.0.7.2/lib/rails/initializable.rb:30:in `instance_exec'
        15: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/railties-5.0.7.2/lib/rails/application/finisher.rb:37:in `block in <module:Finisher>'
        14: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/railties-5.0.7.2/lib/rails/engine.rb:504:in `app'
        13: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/railties-5.0.7.2/lib/rails/engine.rb:504:in `synchronize'
        12: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/railties-5.0.7.2/lib/rails/engine.rb:508:in `block in app'
        11: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/stack.rb:100:in `build'
        10: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/stack.rb:100:in `inject'
         9: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/stack.rb:100:in `each'
         8: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/stack.rb:100:in `block in build'
         7: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/stack.rb:35:in `build'
         6: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/stack.rb:35:in `new'
         5: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/rack-cors-1.0.2/lib/rack/cors.rb:47:in `initialize'
         4: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/rack-cors-1.0.2/lib/rack/cors.rb:47:in `instance_eval'
         3: from /mnt/c/Users/administrateur/pia-back/config/initializers/cors.rb:9:in `block in <top (required)>'
         2: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/rack-cors-1.0.2/lib/rack/cors.rb:62:in `allow'
         1: from /home/administrateur/.rvm/gems/ruby-2.5.5/gems/rack-cors-1.0.2/lib/rack/cors.rb:62:in `instance_eval'
/mnt/c/Users/administrateur/pia-back/config/initializers/cors.rb:10:in `block (2 levels) in <top (required)>': undefined method `split' for nil:NilClass (NoMethodError)

```

Thank you for helpping

**Comment by brunto** [comment]
Hi, you can find the solution here: https://github.com/LINCnil/pia-back/issues/62#issuecomment-480703700

**Comment by Mands59** [comment]
I've Always had the second line in the file "application.example.yml". But not working
