### ISSUE TITLE
probleme connection on postgres when i run "bin/rake db:create"

### ISSUE THREAD

**Issue by Mands59** [LINCnil/pia-back#64]
Thank you for helpping on my last issue, i've a new probs when i "db:create":

```
Running via Spring preloader in process 22915
** Invoke db:create (first_time)
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:create
FATAL:  password authentication failed for user "administrateur"
FATAL:  password authentication failed for user "administrateur"
Couldn't create database for {"adapter"=>"postgresql", "host"=>"localhost", "encoding"=>"unicode", "database"=>"pia_production", "pool"=>5, "username"=>"administrateur", "password"=>"Fiat50012345", "template"=>"template0"}
rake aborted!
PG::ConnectionBad: FATAL:  password authentication failed for user "administrateur"
FATAL:  password authentication failed for user "administrateur"
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/pg-1.0.0/lib/pg.rb:56:in `initialize'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/pg-1.0.0/lib/pg.rb:56:in `new'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/pg-1.0.0/lib/pg.rb:56:in `connect'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/postgresql_adapter.rb:673:in `connect'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/postgresql_adapter.rb:217:in `initialize'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `new'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/activerecord-5.0.7.2/lib/active_record/connection_handling.rb:128:in `retrieve_connection'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/activerecord-5.0.7.2/lib/active_record/connection_handling.rb:91:in `connection'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/activerecord-5.0.7.2/lib/active_record/tasks/postgresql_database_tasks.rb:6:in `connection'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/activerecord-5.0.7.2/lib/active_record/tasks/postgresql_database_tasks.rb:15:in `create'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/activerecord-5.0.7.2/lib/active_record/tasks/database_tasks.rb:109:in `create'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/activerecord-5.0.7.2/lib/active_record/tasks/database_tasks.rb:129:in `block in create_current'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/activerecord-5.0.7.2/lib/active_record/tasks/database_tasks.rb:295:in `block in each_current_configuration'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/activerecord-5.0.7.2/lib/active_record/tasks/database_tasks.rb:292:in `each'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/activerecord-5.0.7.2/lib/active_record/tasks/database_tasks.rb:292:in `each_current_configuration'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/activerecord-5.0.7.2/lib/active_record/tasks/database_tasks.rb:128:in `create_current'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/activerecord-5.0.7.2/lib/active_record/railties/databases.rake:27:in `block (2 levels) in <top (required)>'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/home/administrateur/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/home/administrateur/.rvm/gems/ruby-2.5.5/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/mnt/c/Users/administrateur/pia-back/bin/rake:9:in `<top (required)>'
/home/administrateur/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/administrateur/.rvm/rubies/ruby-2.5.5/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
-e:1:in `<main>'
Tasks: TOP => db:create
```

**Comment by brunto** [comment]
It seems that your password is wrong for your postgres user.
